name: wpbs-stack

services:
  wpbs:
    image: ghcr.io/wpbs-rs/wpbs:0.1.0-rc.1
    #build: .
    container_name: wpbs
    environment:
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
    volumes:
      - ./wpbs/config.yaml:/config.yaml
    restart: unless-stopped
